// @file: /scripts/modules/ui/components/definitionsModalFactory.js
// @version: 3.0 – unified toolbar, search‐in‐header & default layout options

import { createDefinitionModalShell }   from "./definitionModalShell.js";
import { createDefListContainer }       from "../../utils/listUtils.js";
import { createDefinitionListManager }  from "./definitionListManager.js";
import { defaultToolbar, defaultLayoutOptions } from "./modalDefaults.js";

/**
 * @typedef DefinitionModalConfig
 * @property {string} id
 * @property {string} title
 * @property {string|null} [previewType]
 * @property {object} db
 * @property {() => Promise<Array<Object>>} loadDefs
 * @property {(db:object, id:string|null, payload:Object) => Promise<Object>} saveDef
 * @property {(db:object, id:string, payload:Object) => Promise<Object>} updateDef
 * @property {(db:object, id:string) => Promise<void>} deleteDef
 * @property {(callback: (defs:Array<Object>) => void) => () => void} [subscribeDefs]
 * @property {(callbacks:Object) => {
 *   form: HTMLFormElement,
 *   fields: Object,
 *   reset(): void,
 *   populate(def:Object): void,
 *   getCurrent(): Object,
 *   getSubHeaderElement(): HTMLElement,
 *   initPickrs?(): void
 * }} createFormController
 * @property {(def:Object, layout:string, callbacks:Object) => HTMLElement} renderEntry
 * @property {(headerEl:HTMLElement, api:Object) => void} [enhanceHeader]
 * @property {Array<{ icon?: string, label: string, onClick: () => void }>} [toolbar]
 * @property {Array<string>} [layoutOptions]
 */

/**
 * Builds a full CRUD modal with consistent shell, list, preview, and form.
 * Exposes:
 *   - open(): Promise<void>
 *   - refresh(): Promise<void>
 *   - destroy(): void
 */
export function createDefinitionsModal(config) {
  const {
    id,
    title,
    previewType = null,
    db,
    loadDefs,
    saveDef,
    updateDef,
    deleteDef,
    subscribeDefs,
    createFormController,
    renderEntry,
    enhanceHeader,
    // apply defaults if none provided
    toolbar = defaultToolbar,
    layoutOptions = defaultLayoutOptions
  } = config;

  let shell, listApi, formApi, previewApi, unsubscribe;
  let definitions = [];

  async function refreshDefinitions() {
    definitions = await loadDefs();
    listApi.refresh(definitions);
  }

  function startSubscription() {
    if (typeof subscribeDefs !== "function") return;
    unsubscribe?.();
    unsubscribe = subscribeDefs(newDefs => {
      definitions = newDefs;
      listApi.refresh(definitions);
    });
  }

  async function buildIfNeeded() {
    if (shell) return;

    // 1) Create the modal shell with toolbar & layout toggles
    shell = createDefinitionModalShell({
      id,
      title,
      toolbar,
      withPreview: true,
      previewType,
      layoutOptions
    });
    const { header, bodyWrap } = shell;

    // 2) Instantiate form controller
    formApi = createFormController({
      onCancel: async () => {
        formApi.reset();
        previewApi.setFromDefinition({});
        previewApi.show();
      },
      onDelete: async defId => {
        await deleteDef(db, defId);
        await refreshDefinitions();
        formApi.reset();
        previewApi.setFromDefinition({});
        previewApi.show();
      },
      onSubmit: async payload => {
        if (payload.id) {
          await updateDef(db, payload.id, payload);
        } else {
          await saveDef(db, null, payload);
        }
        await refreshDefinitions();
        formApi.reset();
        previewApi.setFromDefinition({});
        previewApi.show();
      }
    });

    // 3) Pull sub-header into the modal header
    const subHeader = formApi.getSubHeaderElement();
    if (subHeader) {
      subHeader.style.marginLeft = "auto";
      header.appendChild(subHeader);
    } else {
      console.warn(`Sub-header not found for modal '${id}'.`);
    }

    // 4) Build & insert the list container + search row will be generated by listManager
    const listContainer = createDefListContainer(`${id}-list`);
    bodyWrap.appendChild(listContainer);
    bodyWrap.appendChild(document.createElement("hr"));

    // 5) Insert the form element
    previewApi = shell.previewApi;
    formApi.form.classList.add("ui-scroll-float");
    bodyWrap.appendChild(formApi.form);

    // 6) Live preview on form input
    formApi.form.addEventListener("input", () => {
      const live = formApi.getCurrent();
      if (live) {
        previewApi.setFromDefinition(live);
        previewApi.show();
      }
    });

    // 7) Wire up the definitions list manager
    listApi = createDefinitionListManager({
      container:      listContainer,
      getDefinitions: () => definitions,
      renderEntry,
      onEntryClick: async def => {
        formApi.populate(def);
        previewApi.setFromDefinition(def);
        previewApi.show();
        _showEditButtons();
      },
      onDelete: async defId => {
        await deleteDef(db, defId);
        await refreshDefinitions();
        formApi.reset();
        previewApi.setFromDefinition({});
        previewApi.show();
        _showAddButtons();
      }
    });

    // 8) Move the auto‐inserted search bar into header (to the right of toolbar)
    const generatedSearch = bodyWrap.querySelector(".list-search");
    if (generatedSearch) {
      generatedSearch.style.margin = "0 0 0 auto";
      header.appendChild(generatedSearch);
    }

    // 9) Allow any extra header controls
    enhanceHeader?.(header, { shell, formApi });
  }

  function _showAddButtons() {
    formApi.showAdd?.();
  }

  function _showEditButtons() {
    formApi.showEdit?.();
  }

  return {
    async open() {
      await buildIfNeeded();

      // subscribe or one‐time load
      if (subscribeDefs) startSubscription();
      else await refreshDefinitions();

      formApi.reset();
      shell.open();
      formApi.initPickrs?.();
      previewApi.setFromDefinition({});
      requestAnimationFrame(() => previewApi.show());
    },

    refresh: refreshDefinitions,

    destroy: () => {
      unsubscribe?.();
      shell?.close?.();
    }
  };
}
