// @file: src/modules/definition/modal/definitionModal.js
// @version: 1.11 — wire `chestSchema.lootPool.items` so the Loot Pool picker isn’t empty

import { createModalShell } from "./lifecycle.js";
import { buildModalUI }     from "./domBuilder.js";
import { definitionTypes }  from "../types.js";
import { loadItemDefinitions } from "../../services/itemDefinitionsService.js";
import { createDefinitionListManager } from "../list/definitionListManager.js";

import { chestSchema } from "../schemas/chestSchema.js"; // ← add this import

export function initDefinitionModal(db) {
  const { modalEl, open, close } =
    createModalShell("definition-modal");
  let {
    header, searchInput, typeSelect,
    listContainer, subheader, formContainer,
    previewContainer
  } = buildModalUI(modalEl);

  let listApi, formApi, previewApi;
  let currentType;
  let definitions = [];
  let definitionsUnsub = null;
  let itemMap = {};

  // Hide preview whenever the modal closes
  modalEl.addEventListener("close", () => {
    if (previewApi) previewApi.hide();
    if (definitionsUnsub) {
      definitionsUnsub();
      definitionsUnsub = null;
    }
  });

  // Reopen on type change
  typeSelect.addEventListener("change", () => {
    openDefinition(typeSelect.value);
  });

  function bindDefinitionUpdates(type) {
    if (definitionsUnsub) {
      definitionsUnsub();
      definitionsUnsub = null;
    }
    const { subscribeDefinitions } = definitionTypes[type];
    if (typeof subscribeDefinitions === "function") {
      definitionsUnsub = subscribeDefinitions(db, defs => {
        definitions = defs;
        listApi.refresh(definitions);
      });
    }
  }

  function setupList() {
    listApi = createDefinitionListManager({
      container:      listContainer,
      getDefinitions: () => definitions,
      onEntryClick:   def => openDefinition(currentType, def),
      onDelete:       async id => {
        if (!confirm("Are you sure you want to delete this definition?")) {
          return;
        }
        await definitionTypes[currentType].del(db, id);
        // subscription will refresh
      }
    });
    searchInput.addEventListener("input", () =>
      listApi.filter(searchInput.value)
    );
  }

  async function openDefinition(type, def = null) {
    currentType = type;
    typeSelect.innerHTML = Object.keys(definitionTypes)
      .map(t => `<option>${t}</option>`).join("");
    typeSelect.value = type;

    if (!listApi) setupList();
    bindDefinitionUpdates(type);

    // ──────────────────────────────────────────────────────────────────────────
    // If this is the Chest type, load all items up front and inject them
    if (type === "Chest") {
      const items = await loadItemDefinitions(db);

      // Build a lookup map for preview‐time enrichment
      itemMap = Object.fromEntries(items.map(i => [i.id, i]));

      // INJECT into the chest schema so that the chip‐list field gets a full catalog:
      // By assigning `chestSchema.lootPool.items = items`, the createFieldRow call
      // (which builds a createChipListField under the hood) will see `opts.items`
      // and pass them into `pickItems(...)`. Without this, the picker is always empty.
      //
      // Note: this mutation is safe here because we only reassign before building
      // the Chest form. Other definition types ignore `lootPool`, so no side effects.
      chestSchema.lootPool.items = items;
    }
    // ──────────────────────────────────────────────────────────────────────────

    previewApi = definitionTypes[type].previewBuilder(previewContainer);

    // Clear any existing form, then build a fresh one.
    formContainer.innerHTML = "";
    formApi = definitionTypes[type].controller({
      title:     type,
      hasFilter: true,
      onCancel:  () => { formApi.reset(); previewApi.hide(); },
      onDelete:  async id => {
        if (!confirm(`Are you sure you want to delete this ${type}?`)) {
          return;
        }
        await definitionTypes[type].del(db, id);
        formApi.reset();
        previewApi.hide();
      },
      onSubmit:  async payload => {
        await definitionTypes[type].save(db, payload.id ?? null, payload);
        formApi.reset();
        previewApi.hide();
      },
      onFieldChange: data => {
        let pd = data;
        if (type === "Chest" && Array.isArray(data.lootPool)) {
          // Convert array of IDs → full item objects for live preview
          pd = {
            ...data,
            lootPool: data.lootPool
              .map(i => itemMap[i])
              .filter(Boolean)
          };
        }
        previewApi.show(pd);
      }
    }, db);

    // Replace the autogenerated subheader element for consistency
    const generated = formApi.form.querySelector(".modal-subheader");
    if (generated && subheader) {
      subheader.replaceWith(generated);
      subheader = generated;
    }

    formContainer.append(formApi.form);
    formApi.initPickrs?.();

    if (def) {
      formApi.populate(def);
    } else {
      formApi.reset();
    }

    open();

    // When first showing, feed preview either existing def (with enrichment)
    // or an empty Chest template so the preview can draw an empty loot list.
    const previewData = def
      ? {
          ...def,
          lootPool: (def.lootPool || [])
            .map(id => itemMap[id])
            .filter(Boolean)
        }
      : { lootPool: [] };
    previewApi.show(previewData);
  }

  return {
    openCreate: (_evt, type = "Item") => openDefinition(type),
    openEdit:   def                   => openDefinition(currentType, def)
  };
}
